name: J2MC_IRC
main: to.joe.j2mc.irc.J2MC_IRC
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: IRC module
commands:
  smackirc:
    description: reloads irc stuff
    usage: /smackirc
    permission: j2mc.irc.management
    permission-message: Chuck Testa
  ircmessage:
    description: send a message on irc to a user
    usage: /ircmessge user message
    permission: j2mc.irc.management
    permission-message: Chuck Testa
permissions:
  j2mc.irc.management:
    description: gives access to /ircmessage and /smackirc